services:
  web:
    image: practicalsre/local-ca:arm-latest
    container_name: web
    restart: unless-stopped
    volumes:
      - db:/app/db
      - static_volume:/app/staticfiles
    networks:
      - app_network
    command: >
      sh -c "
        ls -l
        python manage.py migrate &&
        python manage.py initadmin &&
        python manage.py collectstatic --noinput &&
        exec gunicorn localca_project.wsgi --bind 0.0.0.0:8000 --worker-class=gthread --threads=4"
  nginx:
    image: practicalsre/local-ca-nginx:arm-latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles:ro
    depends_on:
      - web
    networks:
      - app_network

volumes:
  static_volume:
  db:

networks:
  app_network:
    driver: bridge
